version: '3.8'
services:
  app:
    image: koinx-assignment
    build:
      context: .
      args:
        - NODE_ENV=development
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    restart: always
